Repository jduong8/TrendyTravel, pull requests merged in 2023-07, with the labels that each got.

#1 [architecture] Create groups Destination, Category, Activity, User & Renaming files
  TrendyTravel.xcodeproj/project.pbxproj
  TrendyTravel.xcodeproj/project.xcworkspace/xcuserdata/ijoe.xcuserdatad/UserInterfaceState.xcuserstate
  TrendyTravel/Models/Destination.swift
  TrendyTravel/Models/Post.swift
  TrendyTravel/Models/RestaurantDetail.swift
  TrendyTravel/Models/ReviewUser.swift
  TrendyTravel/Models/User.swift
  TrendyTravel/TrendyTravelApp.swift
  TrendyTravel/ViewModel/ActivityDetailViewModel.swift
  TrendyTravel/Views/Activity/ActivityDetailsView.swift
  TrendyTravel/Views/Activity/ActivityReviewList.swift
  TrendyTravel/Views/Activity/ActivityTile.swift
  TrendyTravel/Views/Activity/PopularActivitiesView.swift
  TrendyTravel/Views/Category/CategoriesView.swift
  TrendyTravel/Views/Category/CategoryDetailErrorView.swift
  TrendyTravel/Views/Category/CategoryDetailView.swift
  TrendyTravel/Views/Category/Component/CategoriesIconsView.swift
  TrendyTravel/Views/Category/Component/CategoryDetailCardView.swift
  TrendyTravel/Views/Category/Component/CategoryDetailLoadingView.swift
  TrendyTravel/Views/Destination/Component/CarouselCustomBackground.swift
  TrendyTravel/Views/Destination/Component/CarouselHeaderView.swift
  TrendyTravel/Views/Destination/Component/CustomMapAnnotation.swift
  TrendyTravel/Views/Destination/Component/PopularDestinationTile.swift
  TrendyTravel/Views/Destination/PopularDestinationsDetailsView.swift
  TrendyTravel/Views/Destination/PopularDestinationsView.swift
  TrendyTravel/Views/DiscoverDestinationsView.swift
  TrendyTravel/Views/User/Component/DiscoverUserView.swift
  TrendyTravel/Views/User/TrendingCreatorsView.swift
  TrendyTravel/Views/User/UserDetailsView.swift
Labels: rework

#2 [Category] Rework category model & Display Category list on main screen
  TrendyTravel.xcodeproj/project.xcworkspace/xcuserdata/jonathanduong.xcuserdatad/UserInterfaceState.xcuserstate
  TrendyTravel/Models/Category.swift
  TrendyTravel/Views/Category/CategoriesView.swift
  TrendyTravel/Views/Category/Component/CategoriesIconsView.swift
Labels: rework

#3 fixed caroussel pagination
  TrendyTravel/Views/Destination/Component/CarouselCustomBackground.swift
  TrendyTravel/Views/Destination/Component/CarouselHeaderView.swift
Labels: bug

#7 [Trending Creators]fixed ObservedObject
  TrendyTravel/Views/User/TrendingCreatorsView.swift
  TrendyTravel/Views/User/UsersListView.swift
Labels: bug

#13 [TrendingCreators] Creators Ordered by number of followers
  TrendyTravel/ViewModel/UserViewModel.swift
Labels: enhancement

#14 [activities-list] fix display activities
  TrendyTravel/Models/Destination.swift
  TrendyTravel/ViewModel/ActivityViewModel.swift
  TrendyTravel/ViewModel/DestinationViewModel.swift
  TrendyTravel/Views/Category/CategoriesView.swift
  TrendyTravel/Views/Category/Component/CategoryCardFooterView.swift
  TrendyTravel/Views/Destination/PopularDestinationsDetailsView.swift
Labels: bug, rework

#16 [authentication] Add login & register view
  .gitignore
  TrendyTravel.xcodeproj/project.pbxproj
  TrendyTravel.xcodeproj/project.xcworkspace/xcuserdata/jonathanduong.xcuserdatad/UserInterfaceState.xcuserstate
  TrendyTravel/Models/User.swift
  TrendyTravel/TrendyTravelApp.swift
  TrendyTravel/ViewModel/UserViewModel.swift
  TrendyTravel/Views/Authentication/Component/AuthenticationButtonStyling.swift
  TrendyTravel/Views/Authentication/Component/AuthenticationButtonView.swift
  TrendyTravel/Views/Authentication/Component/DefaultNavigationLinkView.swift
  TrendyTravel/Views/Authentication/Extension/AuthenticationType+Style.swift
  TrendyTravel/Views/Authentication/LoginView.swift
  TrendyTravel/Views/Authentication/Main/AuthenticationView.swift
  TrendyTravel/Views/Authentication/Model/AuthenticationType.swift
  TrendyTravel/Views/Authentication/RegisterView.swift
  TrendyTravel/Views/Authentication/ViewModel/AuthenticationViewModel.swift
  TrendyTravel/Views/DiscoverDestinationsView.swift
  TrendyTravel/Views/User/UserDetailsView.swift
Labels: enhancement

#19 [PostIsLiked] [PostIsFollowed] fix button follow and like
  TrendyTravel.xcodeproj/project.pbxproj
  TrendyTravel/Models/Follower.swift
  TrendyTravel/Models/Post.swift
  TrendyTravel/Models/User.swift
  TrendyTravel/Models/like.swift
  TrendyTravel/ViewModel/UserViewModel.swift
  TrendyTravel/Views/User/Component/DiscoverUserView.swift
  TrendyTravel/Views/User/TrendingCreatorsView.swift
  TrendyTravel/Views/User/UserDetailsView.swift
  TrendyTravel/Views/User/UsersListView.swift
Labels: bug

#20 Feature/pop activities detail view
  TrendyTravel.xcodeproj/project.pbxproj
  TrendyTravel.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  TrendyTravel.xcodeproj/project.xcworkspace/xcuserdata/tatianasimmer.xcuserdatad/UserInterfaceState.xcuserstate
  TrendyTravel/Models/Follower.swift
  TrendyTravel/Models/Like.swift
  TrendyTravel/Models/Review.swift
  TrendyTravel/ViewModel/ActivityDetailViewModel.swift
  TrendyTravel/ViewModel/ActivityReviewViewModel.swift
  TrendyTravel/ViewModel/ActivityViewModel.swift
  TrendyTravel/ViewModel/UserViewModel.swift
  TrendyTravel/Views/Activity/ActivityDetailsView.swift
  TrendyTravel/Views/Activity/ActivityReviewList.swift
  TrendyTravel/Views/Activity/ActivityTile.swift
  TrendyTravel/Views/Activity/Component/ActivityDetailRatingView.swift
  TrendyTravel/Views/Activity/Component/CustomerReviewsCard.swift
  TrendyTravel/Views/Activity/PopularActivitiesView.swift
Labels: enhancement

#23 Feature/pop activities detail view
  TrendyTravel.xcodeproj/project.pbxproj
  TrendyTravel.xcodeproj/project.xcworkspace/xcuserdata/tatianasimmer.xcuserdatad/UserInterfaceState.xcuserstate
  TrendyTravel/Models/Review.swift
  TrendyTravel/Models/User.swift
  TrendyTravel/ViewModel/ActivityDetailViewModel.swift
  TrendyTravel/ViewModel/ActivityReviewViewModel.swift
  TrendyTravel/ViewModel/ActivityViewModel.swift
  TrendyTravel/ViewModel/UserViewModel.swift
  TrendyTravel/Views/Activity/ActivityDetailsView.swift
  TrendyTravel/Views/Activity/ActivityReviewList.swift
  TrendyTravel/Views/Activity/ActivityTile.swift
  TrendyTravel/Views/Activity/Component/ActivityDetailRatingView.swift
  TrendyTravel/Views/Activity/Component/CustomerReviewsCard.swift
  TrendyTravel/Views/Activity/PopularActivitiesView.swift
  TrendyTravel/Views/DiscoverDestinationsView.swift
  TrendyTravel/Views/User/Component/DiscoverUserView.swift
  TrendyTravel/Views/User/UserDetailsView.swift
Labels: bug

#24 [category] navigate to activity detail view
  TrendyTravel.xcodeproj/project.pbxproj
  TrendyTravel/Views/Category/ActivitiesListView.swift
Labels: enhancement

#25 Feature/button contact mail
  TrendyTravel/ViewModel/UserViewModel.swift
  TrendyTravel/Views/User/Component/MailView.swift
  TrendyTravel/Views/User/Component/PostDescriptionView.swift
  TrendyTravel/Views/User/Component/ProfilComponentView.swift
  TrendyTravel/Views/User/UserDetailsView.swift
Labels: bug

#27 [ProfilView] add profilView page
  TrendyTravel/Views/User/ProfilUserVIew.swift
Labels: enhancement

#28 Feature/create review
  TrendyTravel.xcodeproj/project.pbxproj
  TrendyTravel.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  TrendyTravel/Models/Review.swift
  TrendyTravel/ViewModel/ActivityReviewViewModel.swift
  TrendyTravel/Views/Activity/ActivityDetailsView.swift
  TrendyTravel/Views/Activity/AddReviewView.swift
  TrendyTravel/Views/Activity/Component/CustomerReviewsCard.swift
  TrendyTravel/Views/Activity/ShowAddReview.swift
Labels: enhancement

#29 [createUser] add a user
  TrendyTravel.xcodeproj/project.pbxproj
  TrendyTravel/Models/User.swift
  TrendyTravel/ViewModel/ActivityViewModel.swift
  TrendyTravel/ViewModel/UserViewModel.swift
  TrendyTravel/Views/Authentication/LoginView.swift
  TrendyTravel/Views/Authentication/RegisterView.swift
  TrendyTravel/Views/Authentication/ViewModel/AuthenticationViewModel.swift
  TrendyTravel/Views/User/UserDetailsView.swift
Labels: bug, enhancement
